package it.water.connectors.hadoop.api;

import it.water.core.api.service.BaseSystemApi;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods allows interaction with them bypassing permission system.
 */
public interface HadoopConnectorSystemApi extends BaseSystemApi {
    /**
     * It copies file to HDFS
     *
     * @param file         file to copy
     * @param path         HDFS path
     * @param deleteSource Whether delete file if it exists or not
     * @throws IOException IOException
     */
    void upload(File file, String path, boolean deleteSource) throws IOException;

    /**
     * @param pathStr
     * @return
     * @throws IOException
     */
    InputStream download(String pathStr) throws IOException;

    /**
     * @param pathStr
     * @return
     * @throws IOException
     */
    OutputStream appendToFile(String pathStr) throws IOException;

    /**
     * It deletes file
     *
     * @param path Path to file
     * @throws IOException IOException
     */
    void deleteFile(String path) throws IOException;

    /**
     * It deletes folder
     *
     * @param path Path to folder
     */
    void deleteFolder(String path) throws IOException;
}